### ISSUE TITLE
postgresql.azure.jet.crossplane.io should expose a secret with format username@hostname

### ISSUE THREAD

**Issue by msac93** [crossplane-contrib/provider-jet-azure#151]
postgresql.azure.jet.crossplane.io should expose a secret with format username@hostname so that it is compatible with postgresql.sql.crossplane.io which expects a secret in the mentioned format

**Comment by ezgidemirel** [comment]
To be able to use provider-sql Provider with PostgreSQLServer resource of provider-jet-azure, we need to create a ConnectionDetails k8s secret in this [format](https://github.com/crossplane-contrib/provider-sql#usage).
