### ISSUE TITLE
Feature Request - Support for Data Encryption in Azure Postgres Single Server

### ISSUE THREAD

**Issue by shiroyp** [crossplane-contrib/provider-jet-azure#169]
We would like to have support in crossplane to be able create and manage Azure Postgres Single Server with Data Encryption. How this can be done in Azure console is documented here - https://docs.microsoft.com/en-us/azure/postgresql/howto-data-encryption-portal

**Comment by ytsarev** [comment]
@shiroyp does it look like a desired scenario from terraform doc perspective https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_server_key ?
