### ISSUE TITLE
 Feature Request - Support for Data Encryption in Azure SQL

### ISSUE THREAD

**Issue by shiroyp** [crossplane-contrib/provider-jet-azure#170]
We would like to have support in crossplane to be able create and manage Azure Postgres Single Server with Data Encryption. How this can be done in Azure console is documented here - https://docs.microsoft.com/en-us/azure/azure-sql/database/transparent-data-encryption-tde-overview?tabs=azure-portal

**Comment by ytsarev** [comment]
Is this TDE setup satisfies this issue https://github.com/crossplane-contrib/provider-jet-azure/pull/171 ?  

Looks like there is not Database level support for TDE in underlying azurerm provider, see https://github.com/hashicorp/terraform-provider-azurerm/issues/87

So the question is if MSSQLserver level of transparent data encryption will satisfy your scenario?

**Comment by shiroyp** [comment]
I looked at our current code base and looks like it is only running azure sql level TDE at the moment. So for now, we can proceed with Azure SQL Server level TDE Support and include database level TDE support later once the support is available or if there is any additional ask around it.

**Comment by ytsarev** [comment]
@shiroyp that's great, thank you for the feedback!
