### ISSUE TITLE
`azurerm_postgresql_flexible_server_configuration` Resource Configuration Issue

### ISSUE THREAD

**Issue by ulucinar** [crossplane-contrib/provider-jet-azure#99]
### What happened?

`azurerm_postgresql_flexible_server_configuration` Terraform [configuration attributes](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server_configuration) do not include the associated flexible server's name. However, the fully qualified Azure ID refers to its name. Once, ID-based cross-references are available, we can fix this by extracting the name from the referred server's ID.

**Comment by sergenyalcin** [comment]
Hi @ulucinar, it seems that this issue was resolved by the following PR: #103 

https://github.com/crossplane-contrib/provider-jet-azure/blob/df2413436db2f45ecff86b711e25b9d332a26634/config/postgresql/config.go#L57

So I'm closing this issue. Thanks!
